amplify:
  Auth:
    identityPoolId: us-east-1:c79130e7-41ff-4660-b71a-4540a4c66b72
    userPoolId: us-east-1_KRzygmPtY
    userPoolWebClientId: 2s755vegbt7oq6ki2lhc5ao7bn
  Storage:
    bucket: spr-fidelity
apollo:
  url: https://vycn4olkk5cutbghsedrp5xxaq.appsync-api.us-east-1.amazonaws.com/graphql
deploy:
  bucketUrl: s3://import-placement-fidelity.dev.spraoi.ai
  cloudFrontDistributionId: EUQ9A4JCDUEZ5
