amplify:
  Auth:
    identityPoolId: us-east-1:c79130e7-41ff-4660-b71a-4540a4c66b72
    userPoolId: us-east-1_KRzygmPtY
    userPoolWebClientId: 2s755vegbt7oq6ki2lhc5ao7bn
  Storage:
    bucket: spraoi-private-test
apollo:
  url: https://vycn4olkk5cutbghsedrp5xxaq.appsync-api.us-east-1.amazonaws.com/graphql
